media: public/img
content:
  - name: index
    label: Home page
    type: file
    path: content/index.md
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - { name: body, label: Body, type: rich-text }
  - name: metadata
    label: Metadata
    type: file
    path: _data/metadata.js
    format: code
